src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;


use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: CommentaireRepository::class)]
class Commentaire
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "id_commentaire", type: "integer")]
    private ?int $id_commentaire = null;

    #[Assert\NotNull(message: "Le champ post ne peut pas être vide.")]
    #[ORM\ManyToOne(targetEntity: "Post", cascade: ["persist"])]
    #[ORM\JoinColumn(name: "id_publication", nullable: false, referencedColumnName: "id_post")]
    private ?Post $post;

    #[Assert\NotNull(message: "Le champ utilisateur ne peut pas être vide.")]
    #[ORM\ManyToOne(targetEntity: "Utilisateur")]
    #[ORM\JoinColumn(name: "id_utilisateur", nullable: false, referencedColumnName: "id_utilisateur")]
    private ?Utilisateur $utilisateur;

    
    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le champ description_co ne peut pas être vide.")]
    private ?string $description_co = null;

    
    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotNull(message: "Le champ date_co ne peut pas être vide.")]
    private ?\DateTimeInterface $date_co = null;
public function getIdCommentaire(): ?int
    {
        return $this->id_commentaire;
    }

    public function getPost(): ?Post
    {
        return $this->post;
    }

    public function setPost(?Post $post): static
    {
        $this->post = $post;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): static
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getDescriptionCo(): ?string
    {
        return $this->description_co;
    }

    public function setDescriptionCo(string $description_co): static
    {
        $this->description_co = $description_co;

        return $this;
    }

    public function getDateCo(): ?\DateTimeInterface
    {
        return $this->date_co;
    }

    public function setDateCo(\DateTimeInterface $date_co): static
    {
        $this->date_co = $date_co;

        return $this;
    }
}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Utilisateur;
use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('description_co', TextareaType::class, [
            'attr' => ['class' => 'form-control', 'rows' => 5], // Vous pouvez ajuster rows pour modifier la hauteur du champ
            'label' => 'Description :',
            // Ajoutez d'autres options selon vos besoins
        ])
            
            ->add('date_co', DateTimeType::class, [
                'widget' => 'single_text',
                // cela définit la valeur à la date et l'heure actuelles
                'data' => new \DateTime(),
                'attr' => [
                    'class' => 'block w-full mt-1 text-sm dark:border-gray-600 
                    dark:bg-gray-700 focus:border-purple-400 focus:outline-none
                     focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                    'placeholder' => 'jj/mm/année hh:mm',
                    'readonly' => true, // rend le champ en lecture seule
                ],
            ])
            ->add('post', EntityType::class, ['class' => Post::class,
            'choice_label' => 'id_post', 
            // ou tout autre propriété de Utilisateur que vous souhaitez afficher
                             'placeholder' => 'Choisissez une poste', ])
            ->add('utilisateur', EntityType::class, ['class' => Utilisateur::class,
                             'choice_label' => 'id_utilisateur', 
                             // ou tout autre propriété de Utilisateur que vous souhaitez afficher
                                              'placeholder' => 'Choisissez un utilisateur', ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

src/Controller/CommentaireController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Entity\Post;
use App\Form\CommentaireType;
use App\Repository\CommentaireRepository;
use App\Repository\UtilisateurRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



use App\Service\SmsGenerator;

use Symfony\Component\HttpFoundation\Session\SessionInterface;


#[Route('/commentaire')]
class CommentaireController extends AbstractController
{
    #[Route('/', name: 'app_commentaire_index', methods: ['GET'])]
    public function index(CommentaireRepository $commentaireRepository): Response
    {
        return $this->render('commentaire/index.html.twig', [
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }

   

   

    #[Route('/new', name: 'app_commentaire_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            // Tout d'abord, persistez l'entité Commentaire
            $entityManager->persist($commentaire);
            $entityManager->flush();
    
            // Ensuite, mettez à jour le nombre de commentaires dans l'entité Post
            $post = $commentaire->getPost();
            $post->setNbComments($post->getNbComments() + 1);
            $entityManager->persist($post);
            $entityManager->flush();
    
            return $this->redirectToRoute('app_commentaire_index');
        }
    
        return $this->renderForm('commentaire/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }
    
    private $session;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
    }
    
    #[Route('/{id_post}/newFront', name: 'app_commentaire_newFront', methods: ['GET', 'POST'])]
    public function newFront(Request $request, EntityManagerInterface $entityManager,Post $post,UtilisateurRepository $userRepository,SmsGenerator $smsGenerator): Response
    {
         // Créez une instance du PostController pour accéder à la propriété $idUtilisateurConnecte
        

         // Accédez à la propriété $idUtilisateurConnecte
        $idUtilisateurConnecte = $this->session->get('id_utilisateur'); // Retrieve idUtilisateurConnecte from session
        
        $user = $userRepository->find($idUtilisateurConnecte);
        
        $commentaire = new Commentaire();
        $commentaire->setUtilisateur($user);
        $commentaire->setPost($post);
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {




            $badWords = ['mot1', 'mot2', 'mot3']; // Ajoutez ici vos mots interdits
            $commentContent = $commentaire->getDescriptionCo();
            foreach ($badWords as $badWord) {
                if (stripos($commentContent, $badWord) !== false) {
                    // Le commentaire contient un mot interdit
                    // Vous pouvez choisir ici comment vous souhaitez gérer ce cas
                    // Par exemple, vous pouvez ignorer le commentaire ou le signaler
                    // Ici, je vais simplement retourner un message d'erreur
                    // Afficher l'alerte et bloquer l'exécution jusqu'à ce que l'utilisateur appuie sur OK
                     
                    
                    $name=$commentaire->getUtilisateur()->getNom();

                    $text=$commentaire->getDescriptionCo();
            
                    $number_test=$_ENV['twilio_to_number'];// Numéro vérifier par twilio. Un seul numéro autorisé pour la version de test.
            
                    //Appel du service
                    $smsGenerator->sendSms($number_test ,$name,$text);


                    $this->addFlash('error', ' Warning ! Consultez votre SMS pour plus information.'); //lappel teeha fel fichier twig melekher
                

                    return $this->redirectToRoute('app_post_front');
                }
            }



            // Ensuite, mettez à jour le nombre de commentaires dans l'entité Post
            $post = $commentaire->getPost();
            $post->setNbComments($post->getNbComments() + 1);
            $entityManager->persist($post);
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('app_post_front', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentaire/newFront.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    
    #[Route('/{id_commentaire}', name: 'app_commentaire_show', methods: ['GET'])]
    public function show(Commentaire $commentaire): Response
    {
        return $this->render('commentaire/show.html.twig', [
            'commentaire' => $commentaire,
        ]);
    }

    #[Route('/{id_commentaire}/edit', name: 'app_commentaire_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {



            
            $entityManager->flush();
            return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentaire/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }
    #[Route('/{id_commentaire}/editFront', name: 'app_commentaire_editFront', methods: ['GET', 'POST'])]
    public function editFront(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager,SmsGenerator $smsGenerator): Response
    {
        $form = $this->createForm(CommentaireType::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {





            $badWords = ['mot1', 'mot2', 'mot3']; // Ajoutez ici vos mots interdits
            $commentContent = $commentaire->getDescriptionCo();
            foreach ($badWords as $badWord) {
                if (stripos($commentContent, $badWord) !== false) {
                    // Le commentaire contient un mot interdit
                    // Vous pouvez choisir ici comment vous souhaitez gérer ce cas
                    // Par exemple, vous pouvez ignorer le commentaire ou le signaler
                    // Ici, je vais simplement retourner un message d'erreur
                    // Afficher l'alerte et bloquer l'exécution jusqu'à ce que l'utilisateur appuie sur OK
                     
                    
                    $name=$commentaire->getUtilisateur()->getNom();

                    $text=$commentaire->getDescriptionCo();
            
                    $number_test=$_ENV['twilio_to_number'];// Numéro vérifier par twilio. Un seul numéro autorisé pour la version de test.
            
                    //Appel du service
                    $smsGenerator->sendSms($number_test ,$name,$text);


                    $this->addFlash('error', ' Warning ! Consultez votre SMS pour plus information.'); //lappel teeha fel fichier twig melekher
                

                    return $this->redirectToRoute('app_post_front');
                }
            }







            $entityManager->flush();

            return $this->redirectToRoute('app_post_front', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('commentaire/editFront.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form,
        ]);
    }

    #[Route('/{id_commentaire}', name: 'app_commentaire_delete', methods: ['POST'])]
    public function delete(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getIdcommentaire(), $request->request->get('_token'))) {
            $entityManager->remove($commentaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_commentaire_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/front/{id_commentaire}', name: 'app_commentaire_deleteFront', methods: ['POST'])]
    public function deleteFront(Request $request, Commentaire $commentaire, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getIdcommentaire(), $request->request->get('_token'))) {
            $post = $commentaire->getPost();
            $post->setNbComments($post->getNbComments() - 1);
            $entityManager->persist($post);
            $entityManager->remove($commentaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_post_front', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commentaire/_delete_form.html.twig
<form method="post" action="{{ path('app_commentaire_delete', {'id_commentaire': commentaire.getIdCommentaire}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.getIdCommentaire) }}">
    <button class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Delete">
        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
        </svg>
       
    </button>
</form>

templates/commentaire/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/commentaire/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire index{% endblock %}

{% block body %}
<main class="h-full pb-16 overflow-y-auto">
          <div class="container grid px-6 mx-auto">
            <h2
              class="my-6 text-2xl font-semibold text-gray-700 dark:text-gray-200"
            >
              Tables
            </h2>
                     <!-- Search input -->
			<div class="flex justify-center flex-1 lg:mr-32">
				<div class="relative w-full max-w-xl mr-6 focus-within:text-purple-500">
					<div class="absolute inset-y-0 right-0 flex items-center pr-2">
						<svg class="w-4 h-4" aria-hidden="true" fill="currentColor" viewbox="0 0 20 20">
							<path fill-rule="evenodd" d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z" clip-rule="evenodd"></path>
						</svg>
					</div>
					<input id="searchInput" class="w-full pl-8 pr-2 text-sm text-gray-700 placeholder-gray-600 bg-gray-100 border-0 rounded-md dark:placeholder-gray-500 dark:focus:shadow-outline-gray dark:focus:placeholder-gray-600 dark:bg-gray-700 dark:text-gray-200 focus:placeholder-gray-500 focus:bg-white focus:border-purple-300 focus:outline-none focus:shadow-outline-purple form-input" type="text" placeholder="Recherche " aria-label="Search" onkeyup="filterTable()"/>

				</div>
			</div>
            

            <!-- With actions -->
            <h4
              class="mb-4 text-lg font-semibold text-gray-600 dark:text-gray-300"
            >
              <div style="display: flex; justify-content: flex-end;">
  <a href="{{ path('app_commentaire_new') }}">Create new +</a>
</div>
     </h4>
            <div id="tableContainer" class="w-full overflow-hidden rounded-lg shadow-xs">
              <div class="w-full overflow-x-auto">
                <table class="w-full whitespace-no-wrap">
                  <thead>
                    <tr
                      class="text-xs font-semibold tracking-wide text-left text-gray-500 uppercase border-b dark:border-gray-700 bg-gray-50 dark:text-gray-400 dark:bg-gray-800"
                    >
                   
                <th class="px-4 py-3">Username</th>
                <th class="px-4 py-3">Userimage</th> 
                <th class="px-4 py-3">Caption</th>
                <th class="px-4 py-3">Date</th>
                
                <th class="px-4 py-3">Post</th>
                <th class="px-4 py-3">actions</th>
            </tr>
        </thead>
        <tbody
                    class="bg-white divide-y dark:divide-gray-700 dark:bg-gray-800"
                  >
        {% for commentaire in commentaires %}
             <tr class="text-gray-700 dark:text-gray-400">
                   
                   <td class="px-4 py-4">
                        <div class="flex items-center text-sm">
                          <!-- Avatar with inset shadow -->
                         
                          <div>
                            <p class="font-semibold">{{ commentaire.getUtilisateur().getNom()}}</p>
                            
                          </div>
                        </div>
                      </td>
                      <td class="px-4 py-4">
										<div
											class="flex items-center text-sm">
											<!-- Avatar with inset shadow -->
											<div class="relative hidden w-8 h-8 mr-3 rounded-full md:block">
												<img class="object-cover w-full h-full rounded-full" src="{{ asset('images/' ~ commentaire.getUtilisateur().getImage() ) }}" alt="" loading="lazy"/>
												<div class="absolute inset-0 rounded-full shadow-inner" aria-hidden="true"></div>
											</div>
											
										</div>
									</td>  
                        
                <td class="px-4 py-4 text-sm">
                       {{  commentaire.descriptionCo }}
                      </td>
               
               <td class="px-4 py-4 text-sm">
                        {{  commentaire.dateCo ? commentaire.dateCo|date('Y-m-d') : '' }}
                      </td>
                
                  <td class="px-4 py-4">
                        <div class="flex items-center text-sm">
                          <!-- Avatar with inset shadow -->
                         
                          <div>
                            <p class="font-semibold">{{ commentaire.getPost().getIdPost()}}</p>
                            
                          </div>
                        </div>
                      </td>
                <td class="px-4 py-4">
                        <div class="flex items-center space-x-4 text-sm">


                          <a href="{{ path('app_commentaire_show', {'id_commentaire': commentaire.getIdCommentaire}) }}">
                          <button
                           class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                           aria-label="Show"
                            >
                            <svg
                              class="w-5 h-5"
                              aria-hidden="true"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                fill-rule="evenodd"
                               d="M10 2a1 1 0 011 1v1h2a1 1 0 011 1v1h1a1 1 0 011 1v11a1 1 0 01-1 1H3a1 1 0 01-1-1V7a1 1 0 011-1h1V5a1 1 0 011-1h2V3a1 1 0 011-1h4zm-1 7a1 1 0 100 2h2a1 1 0 100-2h-2z"
                              clip-rule="evenodd"
                                ></path>
                            </svg>
                          </button>
                           </a>
                           <a href="{{ path('app_commentaire_edit', {'id_commentaire': commentaire.getIdCommentaire}) }}">
                          <button
                            class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray"
                            aria-label="Edit"
                          >
                            <svg
                              class="w-5 h-5"
                              aria-hidden="true"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                            >
                              <path
                                d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"
                              ></path>
                            </svg>
                          </button>
                           </a>
                            {{ include('commentaire/_delete_form.html.twig', {'commentaire': commentaire}) }}
                        </div>
                      </td>
                    </tr>
                     {% else %}
                      <tr>
                <td colspan="5">no records found</td>
            </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <div
                class="grid px-4 py-3 text-xs font-semibold tracking-wide text-gray-500 uppercase border-t dark:border-gray-700 bg-gray-50 sm:grid-cols-9 dark:text-gray-400 dark:bg-gray-800"
              >
                <span class="flex items-center col-span-3">
                  Showing 21-30 of 100
                </span>
                <span class="col-span-2"></span>
                <!-- Pagination -->
                <span class="flex col-span-4 mt-2 sm:mt-auto sm:justify-end">
                  <nav aria-label="Table navigation">
                    <ul class="inline-flex items-center">
                      <li>
                        <button
                          class="px-3 py-1 rounded-md rounded-l-lg focus:outline-none focus:shadow-outline-purple"
                          aria-label="Previous"
                        >
                          <svg
                            class="w-4 h-4 fill-current"
                            aria-hidden="true"
                            viewBox="0 0 20 20"
                          >
                            <path
                              d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                              clip-rule="evenodd"
                              fill-rule="evenodd"
                            ></path>
                          </svg>
                        </button>
                      </li>
                      <li>
                        <button
                          class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple"
                        >
                          1
                        </button>
                      </li>
                      <li>
                        <button
                          class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple"
                        >
                          2
                        </button>
                      </li>
                      <li>
                        <button
                          class="px-3 py-1 text-white transition-colors duration-150 bg-purple-600 border border-r-0 border-purple-600 rounded-md focus:outline-none focus:shadow-outline-purple"
                        >
                          3
                        </button>
                      </li>
                      <li>
                        <button
                          class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple"
                        >
                          4
                        </button>
                      </li>
                      <li>
                        <span class="px-3 py-1">...</span>
                      </li>
                      <li>
                        <button
                          class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple"
                        >
                          8
                        </button>
                      </li>
                      <li>
                        <button
                          class="px-3 py-1 rounded-md focus:outline-none focus:shadow-outline-purple"
                        >
                          9
                        </button>
                      </li>
                      <li>
                        <button
                          class="px-3 py-1 rounded-md rounded-r-lg focus:outline-none focus:shadow-outline-purple"
                          aria-label="Next"
                        >
                          <svg
                            class="w-4 h-4 fill-current"
                            aria-hidden="true"
                            viewBox="0 0 20 20"
                          >
                            <path
                              d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                              clip-rule="evenodd"
                              fill-rule="evenodd"
                            ></path>
                          </svg>
                        </button>
                      </li>
                    </ul>
                  </nav>
                </span>
              </div>
            </div>
          </div>
        </main>
<script>
		function filterTable() {
var input,
filter,
table,
tbody,
tr,
td,
i,
txtValue;
input = document.getElementById("searchInput");
filter = input.value.toUpperCase();
table = document.getElementById("tableContainer");
tbody = table.getElementsByTagName("tbody")[0];
tr = tbody.getElementsByTagName("tr");
for (i = 0; i < tr.length; i++) {
td = tr[i].getElementsByTagName("td")[0];
if (td) {
txtValue = td.querySelector("p.font-semibold").textContent || td.querySelector("p.font-semibold").innerText;
if (txtValue.toUpperCase().startsWith(filter)) {
tr[i].style.display = "";
} else {
tr[i].style.display = "none";
}
}
}
}
	</script>
{% endblock %}
                

templates/commentaire/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Commentaire{% endblock %}

{% block body %}
    <h1>Commentaire</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id_commentaire</th>
                <td>{{ commentaire.getIdCommentaire }}</td>
            </tr>
            <tr>
                <th>Description_co</th>
                <td>{{ commentaire.descriptionCo }}</td>
            </tr>
            <tr>
                <th>Date_co</th>
                <td>{{ commentaire.dateCo ? commentaire.dateCo|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_commentaire_index') }}">back to list</a>

    <a href="{{ path('app_commentaire_edit', {'id_commentaire': commentaire.getIdCommentaire}) }}">edit</a>

    {{ include('commentaire/_delete_form.html.twig') }}
{% endblock %}