src/Entity/Etablissement.php
<?php

namespace App\Entity;

use App\Repository\EtablissementRepository;
use Doctrine\ORM\Mapping as ORM;


use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: EtablissementRepository::class)]
class Etablissement
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "id_etablissement", type: "integer")]
    private ?int $id_etablissement = null;

    #[ORM\Column(length: 255)]
    #[Assert\Regex(
        pattern: '/[a-zA-Z]/',
        message: "Le nom ne peut pas contenir uniquement des chiffres."
    )]
    #[Assert\NotBlank(message: "Le nom ne peut pas être vide.")]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le lieu ne peut pas être vide.")]
    private ?string $lieu = null;

    #[ORM\Column]
    #[Assert\Positive(
        message: "Le code de l'établissement doit être un nombre positif."
    )]
    #[Assert\Length(
        exactMessage: "Le code de l'établissement doit contenir exactement {{ limit }} chiffres.",
        min: 4,
        max: 4
    )]
    #[Assert\NotBlank(message: "Le Code ne peut pas être vide.")]
    private ?int $code_etablissement = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Le type de l'établissement ne peut pas être vide.")]
    private ?string $type_etablissement = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "L'image ne peut pas être vide.")]
    private ?string $image = null;

    #[ORM\ManyToOne(targetEntity: Utilisateur::class)]
    #[Assert\NotBlank(message: "Veuillez sélectionner un utilisateur.")]
    #[ORM\JoinColumn(name: "id_utilisateur", referencedColumnName: "id_utilisateur", nullable: false)]
    private ?Utilisateur $utilisateur;

    public function getId(): ?int
    {
        return $this->id_etablissement;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): static
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getCodeEtablissement(): ?int
    {
        return $this->code_etablissement;
    }

    public function setCodeEtablissement(int $code_etablissement): static
    {
        $this->code_etablissement = $code_etablissement;

        return $this;
    }

    public function getTypeEtablissement(): ?string
    {
        return $this->type_etablissement;
    }

    public function setTypeEtablissement(string $type_etablissement): static
    {
        $this->type_etablissement = $type_etablissement;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

  



}

src/Form/EtablissementType.php
<?php

namespace App\Form;


use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Utilisateur;

use App\Entity\Etablissement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;





use Symfony\Component\Form\Extension\Core\Type\ChoiceType;



class EtablissementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
        ->add('nom', null, [
            'attr' => [
                'class' => 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                'placeholder' => 'nom'
            ]
        ])

             ->add('lieu', null, [
            'attr' => [
                'class' => 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                'placeholder' => 'lieu'
            ]
        ])
        ->add('code_etablissement', null, [
            'attr' => [
                'class' => 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
                'placeholder' => 'code_etablissement'
            ]
        ])


     // Dans votre formulaire :
->add('type_etablissement', ChoiceType::class, [
    'choices' => [
        'École' => 'ecole',
        'Collège' => 'college',
        'Lycée' => 'lycee',
        'Faculté' => 'faculte',
    ],
    'expanded' => true, // Rend les options sous forme de boutons radio
    'multiple' => false, // Un seul choix est autorisé
    'choice_attr' => function($choice, $key, $value) {
        return ['style' => 'margin-left: 20px; margin-bottom: 10px']; // Ajoute un style inline pour espacer les boutons radio
    },
    'attr' => [
        'class' => 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
        'placeholder' => 'Type'
    ]
])

        
->add('image', null, [
    'attr' => [
        'class' => 'block w-full mt-1 text-sm dark:border-gray-600 dark:bg-gray-700 focus:border-purple-400 focus:outline-none focus:shadow-outline-purple dark:text-gray-300 dark:focus:shadow-outline-gray form-input',
        'placeholder' => 'Image Name',
        'readonly' => true // Ajouter cette ligne pour rendre le champ en lecture seule
    ]
])




            ->add('utilisateur', EntityType::class, [
                'class' => Utilisateur::class,
                'choice_label' => 'nom', // ou tout autre propriété de Utilisateur que vous souhaitez afficher
                'placeholder' => 'Choisissez un utilisateur', // texte à afficher pour le choix vide
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Etablissement::class,
        ]);
    }
}

src/Controller/EtablissementController.php
<?php

namespace App\Controller;

use App\Entity\Etablissement;
use App\Entity\Utilisateur;
use App\Entity\Wallet;
use App\Form\EtablissementType;
use App\Repository\EtablissementRepository;
use App\Repository\UtilisateurRepository;
use App\Repository\WalletRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


use Symfony\Component\HttpFoundation\Session\SessionInterface;



use TCPDF;



use Symfony\Component\HttpFoundation\JsonResponse;


use Symfony\Component\HttpFoundation\RedirectResponse;



use App\Entity\GeoCalculator; // Assurez-vous que le chemin d'accès est correct


#[Route('/etablissement')]
class EtablissementController extends AbstractController
{

    #[Route('/', name: 'app_etablissement_index', methods: ['GET'])]
    public function index(EtablissementRepository $etablissementRepository): Response
    {
  
        return $this->render('etablissement/index.html.twig', [
            'etablissements' => $etablissementRepository->findAll(),
        ]);
    }

    #[Route('/generateEtab_pdf', name: 'generateEtab_pdf')]
    
        public function generatePdf(): Response
        {
            // Créer une instance de TCPDF
            $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    
            // Set document information
            $pdf->SetCreator(PDF_CREATOR);
            $pdf->SetAuthor('Your Name');
            $pdf->SetTitle('Your Title');
            $pdf->SetSubject('Your Subject');
            $pdf->SetKeywords('Your Keywords');
    
            // Supprimer les marges
            $pdf->SetMargins(0, 0, 0);
    
            // Ajouter une nouvelle page
            $pdf->AddPage();
    
            // Obtenir le contenu de la table depuis le template Twig
            $content = $this->renderView('etablissement/pdf.html.twig', [
                'etablissements' => $this->getDoctrine()->getRepository(Etablissement::class)->findAll(), // Récupérer tous les établissements
            ]);
    
            // Écrire le contenu de la table dans le PDF
            $pdf->writeHTML($content, true, false, true, false, '');
    
            // Renvoyer le contenu du PDF comme une réponse avec le type de contenu approprié
            return new Response($pdf->Output('etablissements.pdf', 'D'), 200, [
                'Content-Type' => 'application/pdf',
            ]);
    }
    
    #[Route('/Map', name: 'app_map', methods: ['GET'])]
    public function Map(EntityManagerInterface $entityManager): Response
    {
        $etablissements = $entityManager
            ->getRepository(Etablissement::class)
            ->findAll();
            

        return $this->render('etablissement/map.html.twig', [
            'etablissements' => $etablissements,
            
        ]);
    }


//------------------front---------------------------------

#[Route('/front/Map', name: 'app_mapFront', methods: ['GET'])]
public function MapFront(EtablissementRepository $etablissementRepository,EntityManagerInterface $entityManager): Response
{
    $etablissements = $entityManager
        ->getRepository(Etablissement::class)
        ->findAll();

        $idUtilisateurConnecte = $this->idUtilisateurConnecte;
        

    return $this->render('etablissement/mapFront.html.twig', [
        'etablissements' => $etablissements,
        'idUtilisateurConnecte' => $idUtilisateurConnecte,
        
    ]);
}


private $session;
    public $idUtilisateurConnecte;

    public function __construct(SessionInterface $session)
    {
        $this->session = $session;
        $this->idUtilisateurConnecte = $this->session->get('id_utilisateur');
    }


        
    #[Route('/front', name: 'app_etablissement_front', methods: ['GET'])]
    public function front(EtablissementRepository $etablissementRepository,
    WalletRepository $walletRepository): Response
    {
        
        $idUtilisateurConnecte = $this->idUtilisateurConnecte;
        //$etablissements = $etablissementRepository->findAll(); // Get all establishments
        $etablissements = $etablissementRepository->findByUserId($idUtilisateurConnecte); 

        $etablissementsAndWallets = []; // Initialize empty array

        foreach ($etablissements as $etablissement) {
            $wallets = $walletRepository->findBy(['etablissement' => $etablissement]);

            $etablissementsAndWallets[] = [
                'etablissement' => $etablissement,
                'wallets' => $wallets,
            ];
        }

        return $this->render('etablissement/front.html.twig', [
            'etablissementsAndWallets' => $etablissementsAndWallets,
            'etablissementss' => $etablissementRepository->findAll(),//pour le stats au dessous
        ]);
    }

    #[Route('/newFront', name: 'app_etablissement_newFront', methods: ['GET', 'POST'])]
    public function newFront(Request $request, EntityManagerInterface $entityManager, EtablissementRepository $etablissementRepository,UtilisateurRepository $userRepository ): Response
    {
        $idUtilisateurConnecte = $this->idUtilisateurConnecte;
        $user = $userRepository->find($idUtilisateurConnecte);


        $etablissement = new Etablissement();
        $etablissement->setUtilisateur($user);
        
        $form = $this->createForm(EtablissementType::class, $etablissement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $codeEtablissement = $etablissement->getCodeEtablissement();               
          // Vérifier si le code établissement est unique
          if (!$etablissementRepository->isCodeEtablissementUnique($codeEtablissement)) {
            $this->addFlash('error', 'Le code établissement existe déjà. Veuillez entrer un code unique.'); 
            // Retourner la vue avec les données déjà soumises
            return $this->renderForm('etablissement/newFront.html.twig', [
                'etablissement' => $etablissement,
                'form' => $form,
            ]);
        }
        


            $entityManager->persist($etablissement);
            $entityManager->flush();

            return $this->redirectToRoute('app_etablissement_front', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etablissement/newFront.html.twig', [
            'etablissement' => $etablissement,
            'form' => $form,
        ]);
    }


    #[Route('/front/{id}', name: 'app_etablissement_deleteFront', methods: ['POST'])]
    public function deleteFront(Request $request, Etablissement $etablissement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etablissement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($etablissement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_etablissement_front', [], Response::HTTP_SEE_OTHER);
    }


    #[Route('/front/{id}/edit', name: 'app_etablissement_editFront', methods: ['GET', 'POST'])]
    public function editFront(Request $request, Etablissement $etablissement, EntityManagerInterface $entityManager,EtablissementRepository $etablissementRepository): Response
    {
        $form = $this->createForm(EtablissementType::class, $etablissement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            
            
            
            $codeEtablissement = $etablissement->getCodeEtablissement();               
            // Vérifier si le code établissement est unique
            if (!$etablissementRepository->isCodeEtablissementUnique($codeEtablissement,$etablissement)) {
              $this->addFlash('error', 'Le code établissement existe déjà. Veuillez entrer un code unique.'); 
              // Retourner la vue avec les données déjà soumises
              return $this->renderForm('etablissement/editFront.html.twig', [
                  'etablissement' => $etablissement,
                  'form' => $form,
              ]);
          }
            
            
            
            $entityManager->flush();

            return $this->redirectToRoute('app_etablissement_front', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etablissement/editFront.html.twig', [
            'etablissement' => $etablissement,
            'form' => $form,
        ]);
    }

    //------------------End-Front--------------------




    #[Route('/new', name: 'app_etablissement_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, EtablissementRepository $etablissementRepository): Response
    {
        $etablissement = new Etablissement();
        $form = $this->createForm(EtablissementType::class, $etablissement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {


            $codeEtablissement = $etablissement->getCodeEtablissement();               
          // Vérifier si le code établissement est unique
          if (!$etablissementRepository->isCodeEtablissementUnique($codeEtablissement)) {
            $this->addFlash('error', 'Le code établissement existe déjà. Veuillez entrer un code unique.'); 
            // Retourner la vue avec les données déjà soumises
            return $this->renderForm('etablissement/new.html.twig', [
                'etablissement' => $etablissement,
                'form' => $form,
            ]);
        }
        


            $entityManager->persist($etablissement);
            $entityManager->flush();

            return $this->redirectToRoute('app_etablissement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etablissement/new.html.twig', [

templates/etablissement/_delete_form.html.twig
<form method="post" action="{{ path('app_etablissement_delete', {'id': etablissement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etablissement.id) }}">
    <button class="flex items-center justify-between px-2 py-2 text-sm font-medium leading-5 text-purple-600 rounded-lg dark:text-gray-400 focus:outline-none focus:shadow-outline-gray" aria-label="Delete">
        <svg class="w-5 h-5" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd"></path>
        </svg>
       
    </button>
</form>

templates/etablissement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/etablissement/map.html.twig
{% extends 'base.html.twig' %}

{% block title %}Map{% endblock %}

{% block map %}

<div class="container-xxl bg-primary hero-header">
    <div class="container px-lg-5">
        <div class="row g-5 align-items-center">
            <div class="col-lg-12 text-center">
                <h1 class="text-white mb-4 animated slideInDown">Our Map</h1>
            </div>
        </div>
    </div>
</div>

<div class="art-main-container">
    <div class="art-headline">
        <div class="art-headline__outer art-container">
            <div class="art-headline__inner ">

            </div>
        </div>
    </div>
    <div>
        <br>
        <br>
        <div id="map" style="height: 600px;"></div>
        <p id="coordinates"></p>
    </div>
</div>

<div class="text-center">
    <button class="px-10 py-4 font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple" onclick="centerCameraToLocale()">Center Camera to Locale</button>
</div>

<script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />

<script>
    // Initialize the map with the first etablissement's coordinates
    var firstEtablissementCoords = "{{ etablissements[0].lieu }}".split("-");
    var firstEtablissementLatitude = parseFloat(firstEtablissementCoords[0]);
    var firstEtablissementLongitude = parseFloat(firstEtablissementCoords[1]);
    var map = L.map('map').setView([firstEtablissementLatitude, firstEtablissementLongitude], 10);

    // Add tile layer to the map (OpenStreetMap tiles)
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors'
    }).addTo(map);

    // Add default marker for default establishment
    var defaultIcon = L.icon({
        iconUrl: '{{asset('imagesEtablissements/etablissement.png')}}',
        iconSize: [32, 32],
        iconAnchor: [16, 32],
        popupAnchor: [0, -32]
    });

    var defaultCoords = [36.89896, 10.18980]; // Default coordinates (Paris coordinates for example)
    L.marker(defaultCoords, {icon: defaultIcon}).addTo(map)
        .bindPopup('<b>Notre Locale </b><br>Coordinates: ' + defaultCoords[0] + ', ' + defaultCoords[1]);

    // Add circle with local as center
    var localCircle = L.circle(defaultCoords, {
        color: 'blue',
        fillColor: '#3388ff',
        fillOpacity: 0.5,
        radius: 1000 // Radius in meters
    }).addTo(map);

    // Function to check if coordinates are inside the circle
    function isInCircle(latlng) {
        return localCircle.getBounds().contains(latlng);
    }

    // Function to display coordinates when map is clicked
    function onMapClick(e) {
        var clickedCoordinates = e.latlng;
        document.getElementById("coordinates").innerHTML = "Clicked coordinates: " + clickedCoordinates.lat.toFixed(5) + ", " + clickedCoordinates.lng.toFixed(5);
        // Remove previous temporary marker if exists
        if (tempMarker) {
            map.removeLayer(tempMarker);
        }
        // Add temporary marker
        tempMarker = L.marker(clickedCoordinates).addTo(map);
    }

    map.on('click', onMapClick);

    // Variable to store temporary marker
    var tempMarker;

    // Add markers for events
    {% for etablissement in etablissements %}
    // Extract latitude and longitude from lieu attribute
    var coords = "{{ etablissement.lieu }}".split("-");
    var latitude = parseFloat(coords[0]);
    var longitude = parseFloat(coords[1]);

    // Check if the etablissement is inside the circle
    {#         if (isInCircle([latitude, longitude])) {              #}
    // Define custom icons for different types of places
    var etablissementIcon = L.icon({
        iconUrl: '{{asset('imagesEtablissements/' ~ etablissement.image)}}',
        iconSize: [32, 32],
        iconAnchor: [16, 32],
        popupAnchor: [0, -32]
    });

    // Add marker to the map
    L.marker([latitude, longitude], {icon: etablissementIcon}).addTo(map)
        .bindPopup('<b>{{ etablissement.nom }}</b><br>Pts: {{ etablissement.lieu }}');
    {#           }             #}
    {% endfor %}

    // Fonction pour centrer la caméra à la position de votre locale
    function centerCameraToLocale() {
        // Récupérer les coordonnées de votre locale
        var localeCoords = [36.89896, 10.18980]; // Coordonnées par défaut (à remplacer par les coordonnées de votre locale)

        // Centrer la caméra à la position de votre locale
        map.setView(localeCoords, 15); // 15 est le niveau de zoom, vous pouvez ajuster selon vos besoins
    }
</script>

{% endblock %}

templates/etablissement/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Etablissement
{% endblock %}

{% block body %}
	<div
		x-data="{ isModalOpen: true }">
		<!-- Initialisez la variable isModalOpen à true pour ouvrir le modal par défaut -->
		<div
			x-show="isModalOpen" x-transition:enter="transition ease-out duration-150" x-transition:enter-start="opacity-0 transform translate-y-1/2" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0 transform translate-y-1/2" class="fixed inset-0 z-30 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center">
			<!-- Modal -->
			<div
				x-show="isModalOpen" x-transition:enter="transition ease-out duration-150" x-transition:enter-start="opacity-0 transform translate-y-1/2" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0 transform translate-y-1/2" @click.away="closeModal" @keydown.escape="closeModal" class="w-full max-w-xl px-6 py-4 overflow-hidden bg-white rounded-lg dark:bg-gray-800" role="dialog" id="modal" style="margin: auto">

				<!-- Modal description -->
<div class="modal-description">
  <!-- Modal title -->
  <h2 class="modal-title">Établissement</h2>
  
  <!-- Modal body -->
  <div class="modal-body">
    <table class="modal-table">
      <tbody>
        <tr>
          <th>Nom</th>
          <td>{{ etablissement.nom }}</td>
        </tr>
        <tr>
          <th>Lieu</th>
          <td>{{ etablissement.lieu }}</td>
        </tr>
        <tr>
          <th>Code</th>
          <td>{{ etablissement.codeEtablissement }}</td>
        </tr>
        <tr>
          <th>Type</th>
          <td>{{ etablissement.typeEtablissement }}</td>
        </tr>
        <tr>
          <th>User</th>
          <td>{{ etablissement.getUtilisateur().getNom() }}</td>
        </tr>
        <tr>
          <th>Image</th>
          <td>
            <img src="{{ asset('imagesEtablissements/' ~ etablissement.image) }}" alt="Image de l'établissement {{ etablissement.nom }}" class="etablissement-image"/>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
<style>
.modal-description {
  margin: 1rem 0;
  text-align: center;
  color: #2d3748; /* Gray-700 */
}

.modal-title {
  margin-bottom: 0.5rem;
  font-size: 1.25rem; /* text-lg */
  font-weight: 600; /* font-semibold */
  color: #2d3748; /* Gray-700 */
}

.modal-body {
  display: flex;
  justify-content: center;
}

.modal-table {
  width: 100%;
  border-collapse: collapse;
}

.modal-table th,
.modal-table td {
  padding: 0.5rem; /* px-4 py-2 */
  text-align: left;
}

.modal-table th {
  background-color: #C5B4E3; /* Gray-200 */
  color: #2d3748; /* Gray-700 */
}

.etablissement-image {
  max-width: 100%;
  height: auto;
}
</style>




				<!-- Footer -->
				<footer class="flex justify-center mt-6">
					<!-- Modification de la classe pour centrer horizontalement -->
					<!-- Accept button -->
						<a href="{{ path('app_etablissement_index') }}"> <button @click="closeModal" class="px-4 py-2 text-sm font-medium leading-5 text-white transition-colors duration-150 bg-purple-600 border border-transparent rounded-lg sm:px-4 sm:py-2 active:bg-purple-600 hover:bg-purple-700 focus:outline-none focus:shadow-outline-purple">
							Close
						</button>
					</a>
				</footer>
			</div>
		</div>
	</div>
{% endblock %}